### ISSUE TITLE
Flutter web exception

### ISSUE THREAD

**Issue by hasanm08** [Joran-Dob/flutter_subtitle_wrapper#51]
Error: Unhandled error XMLHttpRequest error. occurred in Instance of 'SubtitleBloc'.
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 909:28                get current
packages/http/src/browser_client.dart 71:22                                                                                    <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1613:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 155:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 707:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 736:13                                        _propagateToListeners        
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 533:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1219:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>

    at Object.throw_ [as throw] (http://localhost:7390/dart_sdk.js:5041:11)
    at http://localhost:7390/packages/bloc/src/bloc_observer.dart.lib.js:155:21
    at subtitle_bloc.SubtitleBloc.new.onError (http://localhost:7390/packages/bloc/src/bloc_observer.dart.lib.js:156:28)
    at _RootZone.runBinaryGuarded (http://localhost:7390/dart_sdk.js:37227:11)
    at sendError (http://localhost:7390/dart_sdk.js:31159:26)
    at _BroadcastSubscription.new.[_sendError] (http://localhost:7390/dart_sdk.js:31176:11)
    at _BroadcastSubscription.new.[_addError] (http://localhost:7390/dart_sdk.js:31102:27)
    at http://localhost:7390/dart_sdk.js:31802:34
    at _SyncBroadcastStreamController.new.[_forEachListener] (http://localhost:7390/dart_sdk.js:31652:13)
    at _SyncBroadcastStreamController.new.[_sendError] (http://localhost:7390/dart_sdk.js:31801:31)
    at _SyncBroadcastStreamController.new.[_addError] (http://localhost:7390/dart_sdk.js:31630:25)
    at _RootZone.runBinaryGuarded (http://localhost:7390/dart_sdk.js:37227:11)
    at sendError (http://localhost:7390/dart_sdk.js:31159:26)
    at _ForwardingStreamSubscription.new.[_sendError] (http://localhost:7390/dart_sdk.js:31176:11)
    at _ForwardingStreamSubscription.new.[_addError] (http://localhost:7390/dart_sdk.js:31102:27)
    at _ForwardingStreamSubscription.new.[_addError] (http://localhost:7390/dart_sdk.js:35161:25)
    at _MapStream.new.[_handleError] (http://localhost:7390/dart_sdk.js:35119:24)
    at _ForwardingStreamSubscription.new.[_handleError] (http://localhost:7390/dart_sdk.js:35186:38)
    at _RootZone.runBinaryGuarded (http://localhost:7390/dart_sdk.js:37227:11)
    at sendError (http://localhost:7390/dart_sdk.js:31159:26)
    at _ControllerSubscription.new.[_sendError] (http://localhost:7390/dart_sdk.js:31176:11)
    at async._DelayedError.new.perform (http://localhost:7390/dart_sdk.js:34444:27)
    at _StreamImplEvents.new.handleNext (http://localhost:7390/dart_sdk.js:34521:15)
    at async._AsyncCallbackEntry.new.callback (http://localhost:7390/dart_sdk.js:34282:16)
    at Object._microtaskLoop (http://localhost:7390/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:7390/dart_sdk.js:37532:13)
    at http://localhost:7390/dart_sdk.js:33303:9

**Comment by hasanm08** [comment]
server problem

:13496/#WebPlayer:1 Access to XMLHttpRequest at 'https://pastebin.com/raw/dXEdh7Xd' from origin 'http://localhost:13496' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
